# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-17 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
